### ISSUE TITLE
nri-prelude fails to build with aeson-2.0

### ISSUE THREAD

**Issue by juhp** [NoRedInk/haskell-libraries#26]
```
nri-prelude      > /tmp/stack-9aa7ce30a97b85ac/nri-prelude-0.6.0.5/src/Log.hs:164:37: error:
nri-prelude      >     • Couldn't match type ‘Data.Text.Internal.Text’ with ‘Aeson.Key’
nri-prelude      >       Expected: Aeson.Key
nri-prelude      >         Actual: Text
nri-prelude      >     • In the first argument of ‘(.=)’, namely ‘key’
nri-prelude      >       In the expression: key .= val
nri-prelude      >       In the first argument of ‘map’, namely
nri-prelude      >         ‘(\ (Context key val) -> key .= val)’
nri-prelude      >     |
nri-prelude      > 164 |       |> map (\(Context key val) -> key .= val)
nri-prelude      >     |                                     ^^^
nri-prelude      > 
nri-prelude      > /tmp/stack-9aa7ce30a97b85ac/nri-prelude-0.6.0.5/src/Log.hs:169:49: error:
nri-prelude      >     • Couldn't match type ‘Data.Text.Internal.Text’ with ‘Aeson.Key’
nri-prelude      >       Expected: Aeson.Key
nri-prelude      >         Actual: Text
nri-prelude      >     • In the first argument of ‘(.=)’, namely ‘key’
nri-prelude      >       In the expression: key .= val
nri-prelude      >       In the first argument of ‘Prelude.foldMap’, namely
nri-prelude      >         ‘(\ (Context key val) -> key .= val)’
nri-prelude      >     |
nri-prelude      > 169 |       |> Prelude.foldMap (\(Context key val) -> key .= val)
nri-prelude      >     |                                                 ^^^
```

**Comment by tankorsmash** [comment]
As a Haskell newcomer, it seems like the way around this is to use a different stack resolver to access older versions.

I was able to get `stack --resolver lts-18.28 build` working, after adding
```
extra-deps:
  nri-prelude---some-version-str, XYZ
```
to my generated `stack.yaml` file.

Not sure what any of it does really, but I got it compiling. If there's a better work around, please let me know!

**Comment by jali-clarke** [comment]
resolved @ https://github.com/NoRedInk/haskell-libraries/pull/97 !

**Comment by tankorsmash** [comment]
Awesome!

Is there a way to get this version of `nri-prelude` onto Stack? It seems like the latest version available is `0.6.0.6`.

edit: Oh, this seems to get close to working:
```yaml
extra-deps:
- git: https://github.com/NoRedInk/haskell-libraries
  commit: f17eefd02b331017d0cf7f465c6bfa2cd0949a12
  subdirs:
    - nri-prelude
```
